### PR TITLE
Remove sp (#42)

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Nowosad** [comment]
Nice. Should we use `r-tmap/tmap` or `r-tmap/tmap@v4`?

**Comment by Nowosad** [comment]
Hi @Robinlovelace -- could you also update the package version?

**Comment by Robinlovelace** [comment]
> Nice. Should we use `r-tmap/tmap` or `r-tmap/tmap@v4`?

Easier to use `r-tmap/tmap` because that will become v4 soon.

**Comment by Robinlovelace** [comment]
Actions are not happy, I'm not sure why.

**Comment by Robinlovelace** [comment]
Aha, seems it still needed `sp`:

```
st_read_sp
```

**Comment by Robinlovelace** [comment]
Working on a fix...

**Pull request merged**
